name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    container:
      image: cypress/base:20.9.0
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install  # Ensure that dependencies are installed before running tests

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          record: true  # Enable recording to Cypress Cloud
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}  # Your Cypress Cloud record key
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for API calls
          CYPRESS_API_TOKEN: ${{ secrets.CYPRESS_API_TOKEN }}  # Add if your tests require it
