name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    container:
      image: cypress/base:20.9.0
      options: --user 1001

    environment: Testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      # Debug step to check environment variables
      - name: Debug environment
        run: printenv | grep CYPRESS
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_API_TOKEN: ${{ secrets.CYPRESS_API_TOKEN }}

      # Debugging API token
      - name: Test API token validity
        run: |
          echo "Testing API Token"
          curl -X GET "https://api

