name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    container:
      image: cypress/base:20.9.0
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run  # runs all tests and uploads results to cypress cloud
        uses: cypress-io/github-action@v6
        with:
          record: true
        env:
          CYPRESS_API_TOKEN: ${{ secrets.CYPRESS_API_TOKEN }} 
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to detect new build vs re-run build
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}