name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    container:
      image: cypress/base:20.9.0
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print Environment Variables (Debugging)
        run: |
          echo "CYPRESS_API_TOKEN: ${{ secrets.CYPRESS_API_TOKEN }}"
          echo "CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}"
          echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
        env:
          CYPRESS_API_TOKEN: ${{ secrets.CYPRESS_API_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
